//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 03:59:37 PM EST 
//


package edu.phema.jaxb.queryHealth.hqmf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POQM_MT000002UV.QualifiedEntityParticipant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POQM_MT000002UV.QualifiedEntityParticipant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="code" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="name" type="{urn:hl7-org:v3}EN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="addr" type="{urn:hl7-org:v3}AD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="telecom" type="{urn:hl7-org:v3}TEL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="statusCode" type="{urn:hl7-org:v3}CS" minOccurs="0"/>
 *         &lt;element name="effectiveTime" type="{urn:hl7-org:v3}IVL_TS" minOccurs="0"/>
 *         &lt;element name="certificateText" type="{urn:hl7-org:v3}ED" minOccurs="0"/>
 *         &lt;element name="confidentialityCode" type="{urn:hl7-org:v3}CE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="quantity" type="{urn:hl7-org:v3}RTO_PQ_PQ" minOccurs="0"/>
 *         &lt;element name="positionNumber" type="{urn:hl7-org:v3}INT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="equivalenceInd" type="{urn:hl7-org:v3}BL" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="qualifiedContainer" type="{urn:hl7-org:v3}POQM_MT000002UV.Container" minOccurs="0"/>
 *           &lt;element name="qualifiedManufacturedMaterial" type="{urn:hl7-org:v3}POQM_MT000002UV.ManufacturedMaterial" minOccurs="0"/>
 *           &lt;element name="qualifiedDevice" type="{urn:hl7-org:v3}POQM_MT000002UV.Device" minOccurs="0"/>
 *           &lt;element name="qualifiedPerson" type="{urn:hl7-org:v3}POQM_MT000002UV.Person" minOccurs="0"/>
 *           &lt;element name="qualifiedNonPersonLivingSubject" type="{urn:hl7-org:v3}POQM_MT000002UV.NonPersonLivingSubject" minOccurs="0"/>
 *           &lt;element name="qualifiedEntity" type="{urn:hl7-org:v3}POQM_MT000002UV.Entity" minOccurs="0"/>
 *           &lt;element name="qualifiedMaterial" type="{urn:hl7-org:v3}POQM_MT000002UV.Material" minOccurs="0"/>
 *           &lt;element name="qualifiedOrganization" type="{urn:hl7-org:v3}POQM_MT000002UV.Organization" minOccurs="0"/>
 *           &lt;element name="qualifiedPlace" type="{urn:hl7-org:v3}POQM_MT000002UV.Place" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="qualificationGrantingContainer" type="{urn:hl7-org:v3}POQM_MT000002UV.Container" minOccurs="0"/>
 *           &lt;element name="qualificationGrantingManufacturedMaterial" type="{urn:hl7-org:v3}POQM_MT000002UV.ManufacturedMaterial" minOccurs="0"/>
 *           &lt;element name="qualificationGrantingDevice" type="{urn:hl7-org:v3}POQM_MT000002UV.Device" minOccurs="0"/>
 *           &lt;element name="qualificationGrantingPerson" type="{urn:hl7-org:v3}POQM_MT000002UV.Person" minOccurs="0"/>
 *           &lt;element name="qualificationGrantingNonPersonLivingSubject" type="{urn:hl7-org:v3}POQM_MT000002UV.NonPersonLivingSubject" minOccurs="0"/>
 *           &lt;element name="qualificationGrantingEntity" type="{urn:hl7-org:v3}POQM_MT000002UV.Entity" minOccurs="0"/>
 *           &lt;element name="qualificationGrantingMaterial" type="{urn:hl7-org:v3}POQM_MT000002UV.Material" minOccurs="0"/>
 *           &lt;element name="qualificationGrantingOrganization" type="{urn:hl7-org:v3}POQM_MT000002UV.Organization" minOccurs="0"/>
 *           &lt;element name="qualificationGrantingPlace" type="{urn:hl7-org:v3}POQM_MT000002UV.Place" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="sourceOf" type="{urn:hl7-org:v3}POQM_MT000002UV.SourceOf3" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="targetOf" type="{urn:hl7-org:v3}POQM_MT000002UV.SourceOf4" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="classCode" use="required" type="{urn:hl7-org:v3}RoleClass" />
 *       &lt;attribute name="negationInd" type="{urn:hl7-org:v3}bl" />
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POQM_MT000002UV.QualifiedEntityParticipant", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "id",
    "code",
    "name",
    "addr",
    "telecom",
    "statusCode",
    "effectiveTime",
    "certificateText",
    "confidentialityCode",
    "quantity",
    "positionNumber",
    "equivalenceInd",
    "qualifiedContainer",
    "qualifiedManufacturedMaterial",
    "qualifiedDevice",
    "qualifiedPerson",
    "qualifiedNonPersonLivingSubject",
    "qualifiedEntity",
    "qualifiedMaterial",
    "qualifiedOrganization",
    "qualifiedPlace",
    "qualificationGrantingContainer",
    "qualificationGrantingManufacturedMaterial",
    "qualificationGrantingDevice",
    "qualificationGrantingPerson",
    "qualificationGrantingNonPersonLivingSubject",
    "qualificationGrantingEntity",
    "qualificationGrantingMaterial",
    "qualificationGrantingOrganization",
    "qualificationGrantingPlace",
    "sourceOf",
    "targetOf"
})
public class POQMMT000002UVQualifiedEntityParticipant {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    protected List<II> id;
    protected CE code;
    protected List<EN> name;
    protected List<AD> addr;
    protected List<TEL> telecom;
    protected CS statusCode;
    protected IVLTS effectiveTime;
    protected ED certificateText;
    protected List<CE> confidentialityCode;
    protected RTOPQPQ quantity;
    protected List<INT> positionNumber;
    protected BL equivalenceInd;
    protected POQMMT000002UVContainer qualifiedContainer;
    protected POQMMT000002UVManufacturedMaterial qualifiedManufacturedMaterial;
    protected POQMMT000002UVDevice qualifiedDevice;
    protected POQMMT000002UVPerson qualifiedPerson;
    protected POQMMT000002UVNonPersonLivingSubject qualifiedNonPersonLivingSubject;
    protected POQMMT000002UVEntity qualifiedEntity;
    protected POQMMT000002UVMaterial qualifiedMaterial;
    protected POQMMT000002UVOrganization qualifiedOrganization;
    protected POQMMT000002UVPlace qualifiedPlace;
    protected POQMMT000002UVContainer qualificationGrantingContainer;
    protected POQMMT000002UVManufacturedMaterial qualificationGrantingManufacturedMaterial;
    protected POQMMT000002UVDevice qualificationGrantingDevice;
    protected POQMMT000002UVPerson qualificationGrantingPerson;
    protected POQMMT000002UVNonPersonLivingSubject qualificationGrantingNonPersonLivingSubject;
    protected POQMMT000002UVEntity qualificationGrantingEntity;
    protected POQMMT000002UVMaterial qualificationGrantingMaterial;
    protected POQMMT000002UVOrganization qualificationGrantingOrganization;
    protected POQMMT000002UVPlace qualificationGrantingPlace;
    protected List<POQMMT000002UVSourceOf3> sourceOf;
    protected List<POQMMT000002UVSourceOf4> targetOf;
    @XmlAttribute(required = true)
    protected RoleClass classCode;
    @XmlAttribute
    protected Boolean negationInd;
    @XmlAttribute
    protected NullFlavor nullFlavor;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getId() {
        if (id == null) {
            id = new ArrayList<II>();
        }
        return this.id;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CE }
     *     
     */
    public CE getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CE }
     *     
     */
    public void setCode(CE value) {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EN }
     * 
     * 
     */
    public List<EN> getName() {
        if (name == null) {
            name = new ArrayList<EN>();
        }
        return this.name;
    }

    /**
     * Gets the value of the addr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AD }
     * 
     * 
     */
    public List<AD> getAddr() {
        if (addr == null) {
            addr = new ArrayList<AD>();
        }
        return this.addr;
    }

    /**
     * Gets the value of the telecom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telecom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelecom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEL }
     * 
     * 
     */
    public List<TEL> getTelecom() {
        if (telecom == null) {
            telecom = new ArrayList<TEL>();
        }
        return this.telecom;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setStatusCode(CS value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the effectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * Sets the value of the effectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setEffectiveTime(IVLTS value) {
        this.effectiveTime = value;
    }

    /**
     * Gets the value of the certificateText property.
     * 
     * @return
     *     possible object is
     *     {@link ED }
     *     
     */
    public ED getCertificateText() {
        return certificateText;
    }

    /**
     * Sets the value of the certificateText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ED }
     *     
     */
    public void setCertificateText(ED value) {
        this.certificateText = value;
    }

    /**
     * Gets the value of the confidentialityCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the confidentialityCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfidentialityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CE }
     * 
     * 
     */
    public List<CE> getConfidentialityCode() {
        if (confidentialityCode == null) {
            confidentialityCode = new ArrayList<CE>();
        }
        return this.confidentialityCode;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link RTOPQPQ }
     *     
     */
    public RTOPQPQ getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTOPQPQ }
     *     
     */
    public void setQuantity(RTOPQPQ value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the positionNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the positionNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositionNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INT }
     * 
     * 
     */
    public List<INT> getPositionNumber() {
        if (positionNumber == null) {
            positionNumber = new ArrayList<INT>();
        }
        return this.positionNumber;
    }

    /**
     * Gets the value of the equivalenceInd property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getEquivalenceInd() {
        return equivalenceInd;
    }

    /**
     * Sets the value of the equivalenceInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setEquivalenceInd(BL value) {
        this.equivalenceInd = value;
    }

    /**
     * Gets the value of the qualifiedContainer property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVContainer }
     *     
     */
    public POQMMT000002UVContainer getQualifiedContainer() {
        return qualifiedContainer;
    }

    /**
     * Sets the value of the qualifiedContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVContainer }
     *     
     */
    public void setQualifiedContainer(POQMMT000002UVContainer value) {
        this.qualifiedContainer = value;
    }

    /**
     * Gets the value of the qualifiedManufacturedMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVManufacturedMaterial }
     *     
     */
    public POQMMT000002UVManufacturedMaterial getQualifiedManufacturedMaterial() {
        return qualifiedManufacturedMaterial;
    }

    /**
     * Sets the value of the qualifiedManufacturedMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVManufacturedMaterial }
     *     
     */
    public void setQualifiedManufacturedMaterial(POQMMT000002UVManufacturedMaterial value) {
        this.qualifiedManufacturedMaterial = value;
    }

    /**
     * Gets the value of the qualifiedDevice property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVDevice }
     *     
     */
    public POQMMT000002UVDevice getQualifiedDevice() {
        return qualifiedDevice;
    }

    /**
     * Sets the value of the qualifiedDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVDevice }
     *     
     */
    public void setQualifiedDevice(POQMMT000002UVDevice value) {
        this.qualifiedDevice = value;
    }

    /**
     * Gets the value of the qualifiedPerson property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPerson }
     *     
     */
    public POQMMT000002UVPerson getQualifiedPerson() {
        return qualifiedPerson;
    }

    /**
     * Sets the value of the qualifiedPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPerson }
     *     
     */
    public void setQualifiedPerson(POQMMT000002UVPerson value) {
        this.qualifiedPerson = value;
    }

    /**
     * Gets the value of the qualifiedNonPersonLivingSubject property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVNonPersonLivingSubject }
     *     
     */
    public POQMMT000002UVNonPersonLivingSubject getQualifiedNonPersonLivingSubject() {
        return qualifiedNonPersonLivingSubject;
    }

    /**
     * Sets the value of the qualifiedNonPersonLivingSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVNonPersonLivingSubject }
     *     
     */
    public void setQualifiedNonPersonLivingSubject(POQMMT000002UVNonPersonLivingSubject value) {
        this.qualifiedNonPersonLivingSubject = value;
    }

    /**
     * Gets the value of the qualifiedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVEntity }
     *     
     */
    public POQMMT000002UVEntity getQualifiedEntity() {
        return qualifiedEntity;
    }

    /**
     * Sets the value of the qualifiedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVEntity }
     *     
     */
    public void setQualifiedEntity(POQMMT000002UVEntity value) {
        this.qualifiedEntity = value;
    }

    /**
     * Gets the value of the qualifiedMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVMaterial }
     *     
     */
    public POQMMT000002UVMaterial getQualifiedMaterial() {
        return qualifiedMaterial;
    }

    /**
     * Sets the value of the qualifiedMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVMaterial }
     *     
     */
    public void setQualifiedMaterial(POQMMT000002UVMaterial value) {
        this.qualifiedMaterial = value;
    }

    /**
     * Gets the value of the qualifiedOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVOrganization }
     *     
     */
    public POQMMT000002UVOrganization getQualifiedOrganization() {
        return qualifiedOrganization;
    }

    /**
     * Sets the value of the qualifiedOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVOrganization }
     *     
     */
    public void setQualifiedOrganization(POQMMT000002UVOrganization value) {
        this.qualifiedOrganization = value;
    }

    /**
     * Gets the value of the qualifiedPlace property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPlace }
     *     
     */
    public POQMMT000002UVPlace getQualifiedPlace() {
        return qualifiedPlace;
    }

    /**
     * Sets the value of the qualifiedPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPlace }
     *     
     */
    public void setQualifiedPlace(POQMMT000002UVPlace value) {
        this.qualifiedPlace = value;
    }

    /**
     * Gets the value of the qualificationGrantingContainer property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVContainer }
     *     
     */
    public POQMMT000002UVContainer getQualificationGrantingContainer() {
        return qualificationGrantingContainer;
    }

    /**
     * Sets the value of the qualificationGrantingContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVContainer }
     *     
     */
    public void setQualificationGrantingContainer(POQMMT000002UVContainer value) {
        this.qualificationGrantingContainer = value;
    }

    /**
     * Gets the value of the qualificationGrantingManufacturedMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVManufacturedMaterial }
     *     
     */
    public POQMMT000002UVManufacturedMaterial getQualificationGrantingManufacturedMaterial() {
        return qualificationGrantingManufacturedMaterial;
    }

    /**
     * Sets the value of the qualificationGrantingManufacturedMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVManufacturedMaterial }
     *     
     */
    public void setQualificationGrantingManufacturedMaterial(POQMMT000002UVManufacturedMaterial value) {
        this.qualificationGrantingManufacturedMaterial = value;
    }

    /**
     * Gets the value of the qualificationGrantingDevice property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVDevice }
     *     
     */
    public POQMMT000002UVDevice getQualificationGrantingDevice() {
        return qualificationGrantingDevice;
    }

    /**
     * Sets the value of the qualificationGrantingDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVDevice }
     *     
     */
    public void setQualificationGrantingDevice(POQMMT000002UVDevice value) {
        this.qualificationGrantingDevice = value;
    }

    /**
     * Gets the value of the qualificationGrantingPerson property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPerson }
     *     
     */
    public POQMMT000002UVPerson getQualificationGrantingPerson() {
        return qualificationGrantingPerson;
    }

    /**
     * Sets the value of the qualificationGrantingPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPerson }
     *     
     */
    public void setQualificationGrantingPerson(POQMMT000002UVPerson value) {
        this.qualificationGrantingPerson = value;
    }

    /**
     * Gets the value of the qualificationGrantingNonPersonLivingSubject property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVNonPersonLivingSubject }
     *     
     */
    public POQMMT000002UVNonPersonLivingSubject getQualificationGrantingNonPersonLivingSubject() {
        return qualificationGrantingNonPersonLivingSubject;
    }

    /**
     * Sets the value of the qualificationGrantingNonPersonLivingSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVNonPersonLivingSubject }
     *     
     */
    public void setQualificationGrantingNonPersonLivingSubject(POQMMT000002UVNonPersonLivingSubject value) {
        this.qualificationGrantingNonPersonLivingSubject = value;
    }

    /**
     * Gets the value of the qualificationGrantingEntity property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVEntity }
     *     
     */
    public POQMMT000002UVEntity getQualificationGrantingEntity() {
        return qualificationGrantingEntity;
    }

    /**
     * Sets the value of the qualificationGrantingEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVEntity }
     *     
     */
    public void setQualificationGrantingEntity(POQMMT000002UVEntity value) {
        this.qualificationGrantingEntity = value;
    }

    /**
     * Gets the value of the qualificationGrantingMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVMaterial }
     *     
     */
    public POQMMT000002UVMaterial getQualificationGrantingMaterial() {
        return qualificationGrantingMaterial;
    }

    /**
     * Sets the value of the qualificationGrantingMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVMaterial }
     *     
     */
    public void setQualificationGrantingMaterial(POQMMT000002UVMaterial value) {
        this.qualificationGrantingMaterial = value;
    }

    /**
     * Gets the value of the qualificationGrantingOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVOrganization }
     *     
     */
    public POQMMT000002UVOrganization getQualificationGrantingOrganization() {
        return qualificationGrantingOrganization;
    }

    /**
     * Sets the value of the qualificationGrantingOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVOrganization }
     *     
     */
    public void setQualificationGrantingOrganization(POQMMT000002UVOrganization value) {
        this.qualificationGrantingOrganization = value;
    }

    /**
     * Gets the value of the qualificationGrantingPlace property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPlace }
     *     
     */
    public POQMMT000002UVPlace getQualificationGrantingPlace() {
        return qualificationGrantingPlace;
    }

    /**
     * Sets the value of the qualificationGrantingPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPlace }
     *     
     */
    public void setQualificationGrantingPlace(POQMMT000002UVPlace value) {
        this.qualificationGrantingPlace = value;
    }

    /**
     * Gets the value of the sourceOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVSourceOf3 }
     * 
     * 
     */
    public List<POQMMT000002UVSourceOf3> getSourceOf() {
        if (sourceOf == null) {
            sourceOf = new ArrayList<POQMMT000002UVSourceOf3>();
        }
        return this.sourceOf;
    }

    /**
     * Gets the value of the targetOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVSourceOf4 }
     * 
     * 
     */
    public List<POQMMT000002UVSourceOf4> getTargetOf() {
        if (targetOf == null) {
            targetOf = new ArrayList<POQMMT000002UVSourceOf4>();
        }
        return this.targetOf;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link RoleClass }
     *     
     */
    public RoleClass getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleClass }
     *     
     */
    public void setClassCode(RoleClass value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the negationInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNegationInd() {
        return negationInd;
    }

    /**
     * Sets the value of the negationInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNegationInd(Boolean value) {
        this.negationInd = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * @return
     *     possible object is
     *     {@link NullFlavor }
     *     
     */
    public NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    /**
     * Sets the value of the nullFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullFlavor }
     *     
     */
    public void setNullFlavor(NullFlavor value) {
        this.nullFlavor = value;
    }

}
