//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 03:59:37 PM EST 
//


package edu.phema.jaxb.queryHealth.hqmf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POQM_MT000002UV.Precondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POQM_MT000002UV.Precondition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="localVariableName" type="{urn:hl7-org:v3}ST" minOccurs="0"/>
 *         &lt;element name="conjunctionCode" type="{urn:hl7-org:v3}CS" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;group ref="{urn:hl7-org:v3}POQM_MT000002UV.PreconditionChoice"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *       &lt;attribute name="typeCode" type="{urn:hl7-org:v3}ActRelationshipType" fixed="COMP" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POQM_MT000002UV.Precondition", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "localVariableName",
    "conjunctionCode",
    "allTrue",
    "allFalse",
    "atLeastOneTrue",
    "atLeastOneFalse",
    "onlyOneTrue",
    "onlyOneFalse",
    "actReference",
    "substanceAdministrationReference",
    "encounterReference",
    "observationReference",
    "procedureReference",
    "supplyReference"
})
public class POQMMT000002UVPrecondition {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    protected ST localVariableName;
    protected CS conjunctionCode;
    protected POQMMT000002UVAllTrue allTrue;
    protected POQMMT000002UVAllFalse allFalse;
    protected POQMMT000002UVAtLeastOneTrue atLeastOneTrue;
    protected POQMMT000002UVAtLeastOneFalse atLeastOneFalse;
    protected POQMMT000002UVOnlyOneTrue onlyOneTrue;
    protected POQMMT000002UVOnlyOneFalse onlyOneFalse;
    protected POQMMT000002UVActReference actReference;
    protected POQMMT000002UVSubstanceAdministrationReference substanceAdministrationReference;
    protected POQMMT000002UVEncounterReference encounterReference;
    protected POQMMT000002UVObservationReference observationReference;
    protected POQMMT000002UVProcedureReference procedureReference;
    protected POQMMT000002UVSupplyReference supplyReference;
    @XmlAttribute
    protected NullFlavor nullFlavor;
    @XmlAttribute
    protected ActRelationshipType typeCode;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the localVariableName property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getLocalVariableName() {
        return localVariableName;
    }

    /**
     * Sets the value of the localVariableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setLocalVariableName(ST value) {
        this.localVariableName = value;
    }

    /**
     * Gets the value of the conjunctionCode property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getConjunctionCode() {
        return conjunctionCode;
    }

    /**
     * Sets the value of the conjunctionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setConjunctionCode(CS value) {
        this.conjunctionCode = value;
    }

    /**
     * Gets the value of the allTrue property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVAllTrue }
     *     
     */
    public POQMMT000002UVAllTrue getAllTrue() {
        return allTrue;
    }

    /**
     * Sets the value of the allTrue property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVAllTrue }
     *     
     */
    public void setAllTrue(POQMMT000002UVAllTrue value) {
        this.allTrue = value;
    }

    /**
     * Gets the value of the allFalse property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVAllFalse }
     *     
     */
    public POQMMT000002UVAllFalse getAllFalse() {
        return allFalse;
    }

    /**
     * Sets the value of the allFalse property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVAllFalse }
     *     
     */
    public void setAllFalse(POQMMT000002UVAllFalse value) {
        this.allFalse = value;
    }

    /**
     * Gets the value of the atLeastOneTrue property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVAtLeastOneTrue }
     *     
     */
    public POQMMT000002UVAtLeastOneTrue getAtLeastOneTrue() {
        return atLeastOneTrue;
    }

    /**
     * Sets the value of the atLeastOneTrue property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVAtLeastOneTrue }
     *     
     */
    public void setAtLeastOneTrue(POQMMT000002UVAtLeastOneTrue value) {
        this.atLeastOneTrue = value;
    }

    /**
     * Gets the value of the atLeastOneFalse property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVAtLeastOneFalse }
     *     
     */
    public POQMMT000002UVAtLeastOneFalse getAtLeastOneFalse() {
        return atLeastOneFalse;
    }

    /**
     * Sets the value of the atLeastOneFalse property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVAtLeastOneFalse }
     *     
     */
    public void setAtLeastOneFalse(POQMMT000002UVAtLeastOneFalse value) {
        this.atLeastOneFalse = value;
    }

    /**
     * Gets the value of the onlyOneTrue property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVOnlyOneTrue }
     *     
     */
    public POQMMT000002UVOnlyOneTrue getOnlyOneTrue() {
        return onlyOneTrue;
    }

    /**
     * Sets the value of the onlyOneTrue property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVOnlyOneTrue }
     *     
     */
    public void setOnlyOneTrue(POQMMT000002UVOnlyOneTrue value) {
        this.onlyOneTrue = value;
    }

    /**
     * Gets the value of the onlyOneFalse property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVOnlyOneFalse }
     *     
     */
    public POQMMT000002UVOnlyOneFalse getOnlyOneFalse() {
        return onlyOneFalse;
    }

    /**
     * Sets the value of the onlyOneFalse property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVOnlyOneFalse }
     *     
     */
    public void setOnlyOneFalse(POQMMT000002UVOnlyOneFalse value) {
        this.onlyOneFalse = value;
    }

    /**
     * Gets the value of the actReference property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVActReference }
     *     
     */
    public POQMMT000002UVActReference getActReference() {
        return actReference;
    }

    /**
     * Sets the value of the actReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVActReference }
     *     
     */
    public void setActReference(POQMMT000002UVActReference value) {
        this.actReference = value;
    }

    /**
     * Gets the value of the substanceAdministrationReference property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVSubstanceAdministrationReference }
     *     
     */
    public POQMMT000002UVSubstanceAdministrationReference getSubstanceAdministrationReference() {
        return substanceAdministrationReference;
    }

    /**
     * Sets the value of the substanceAdministrationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVSubstanceAdministrationReference }
     *     
     */
    public void setSubstanceAdministrationReference(POQMMT000002UVSubstanceAdministrationReference value) {
        this.substanceAdministrationReference = value;
    }

    /**
     * Gets the value of the encounterReference property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVEncounterReference }
     *     
     */
    public POQMMT000002UVEncounterReference getEncounterReference() {
        return encounterReference;
    }

    /**
     * Sets the value of the encounterReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVEncounterReference }
     *     
     */
    public void setEncounterReference(POQMMT000002UVEncounterReference value) {
        this.encounterReference = value;
    }

    /**
     * Gets the value of the observationReference property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVObservationReference }
     *     
     */
    public POQMMT000002UVObservationReference getObservationReference() {
        return observationReference;
    }

    /**
     * Sets the value of the observationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVObservationReference }
     *     
     */
    public void setObservationReference(POQMMT000002UVObservationReference value) {
        this.observationReference = value;
    }

    /**
     * Gets the value of the procedureReference property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVProcedureReference }
     *     
     */
    public POQMMT000002UVProcedureReference getProcedureReference() {
        return procedureReference;
    }

    /**
     * Sets the value of the procedureReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVProcedureReference }
     *     
     */
    public void setProcedureReference(POQMMT000002UVProcedureReference value) {
        this.procedureReference = value;
    }

    /**
     * Gets the value of the supplyReference property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVSupplyReference }
     *     
     */
    public POQMMT000002UVSupplyReference getSupplyReference() {
        return supplyReference;
    }

    /**
     * Sets the value of the supplyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVSupplyReference }
     *     
     */
    public void setSupplyReference(POQMMT000002UVSupplyReference value) {
        this.supplyReference = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * @return
     *     possible object is
     *     {@link NullFlavor }
     *     
     */
    public NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    /**
     * Sets the value of the nullFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullFlavor }
     *     
     */
    public void setNullFlavor(NullFlavor value) {
        this.nullFlavor = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link ActRelationshipType }
     *     
     */
    public ActRelationshipType getTypeCode() {
        if (typeCode == null) {
            return ActRelationshipType.COMP;
        } else {
            return typeCode;
        }
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActRelationshipType }
     *     
     */
    public void setTypeCode(ActRelationshipType value) {
        this.typeCode = value;
    }

}
