//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 03:59:37 PM EST 
//


package edu.phema.jaxb.queryHealth.hqmf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POQM_MT000002UV.Device complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POQM_MT000002UV.Device">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="code" type="{urn:hl7-org:v3}CD" minOccurs="0"/>
 *         &lt;element name="quantity" type="{urn:hl7-org:v3}PQ" minOccurs="0"/>
 *         &lt;element name="name" type="{urn:hl7-org:v3}EN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="desc" type="{urn:hl7-org:v3}ED" minOccurs="0"/>
 *         &lt;element name="statusCode" type="{urn:hl7-org:v3}CS" minOccurs="0"/>
 *         &lt;element name="existenceTime" type="{urn:hl7-org:v3}IVL_TS" minOccurs="0"/>
 *         &lt;element name="telecom" type="{urn:hl7-org:v3}TEL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="riskCode" type="{urn:hl7-org:v3}CE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="handlingCode" type="{urn:hl7-org:v3}CE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="formCode" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="lotNumberText" type="{urn:hl7-org:v3}ST" minOccurs="0"/>
 *         &lt;element name="expirationTime" type="{urn:hl7-org:v3}IVL_TS" minOccurs="0"/>
 *         &lt;element name="stabilityTime" type="{urn:hl7-org:v3}IVL_TS" minOccurs="0"/>
 *         &lt;element name="manufacturerModelName" type="{urn:hl7-org:v3}SC" minOccurs="0"/>
 *         &lt;element name="softwareName" type="{urn:hl7-org:v3}SC" minOccurs="0"/>
 *         &lt;element name="localRemoteControlStateCode" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="alertLevelCode" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="lastCalibrationTime" type="{urn:hl7-org:v3}TS" minOccurs="0"/>
 *         &lt;element name="asPatientParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.PatientParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="asLicensedEntityParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.LicensedEntityParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="asEmploymentParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.EmploymentParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="asQualifiedEntityParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.QualifiedEntityParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="asAccessParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.AccessParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="asRoleParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.RoleParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="asRolePlayed" type="{urn:hl7-org:v3}POQM_MT000002UV.RolePlayed" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patientParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.PatientParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="licensedEntityParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.LicensedEntityParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="employmentParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.EmploymentParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qualifiedEntityParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.QualifiedEntityParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="accessParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.AccessParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="roleParticipation" type="{urn:hl7-org:v3}POQM_MT000002UV.RoleParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="roleScoped" type="{urn:hl7-org:v3}POQM_MT000002UV.RoleScoped" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="languageCommunication" type="{urn:hl7-org:v3}POQM_MT000002UV.LanguageCommunication" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="classCode" use="required" type="{urn:hl7-org:v3}EntityClass" />
 *       &lt;attribute name="determinerCode" use="required" type="{urn:hl7-org:v3}EntityDeterminer" />
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POQM_MT000002UV.Device", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "id",
    "code",
    "quantity",
    "name",
    "desc",
    "statusCode",
    "existenceTime",
    "telecom",
    "riskCode",
    "handlingCode",
    "formCode",
    "lotNumberText",
    "expirationTime",
    "stabilityTime",
    "manufacturerModelName",
    "softwareName",
    "localRemoteControlStateCode",
    "alertLevelCode",
    "lastCalibrationTime",
    "asPatientParticipation",
    "asLicensedEntityParticipation",
    "asEmploymentParticipation",
    "asQualifiedEntityParticipation",
    "asAccessParticipation",
    "asRoleParticipation",
    "asRolePlayed",
    "patientParticipation",
    "licensedEntityParticipation",
    "employmentParticipation",
    "qualifiedEntityParticipation",
    "accessParticipation",
    "roleParticipation",
    "roleScoped",
    "languageCommunication"
})
public class POQMMT000002UVDevice {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    protected List<II> id;
    protected CD code;
    protected PQ quantity;
    protected List<EN> name;
    protected ED desc;
    protected CS statusCode;
    protected IVLTS existenceTime;
    protected List<TEL> telecom;
    protected List<CE> riskCode;
    protected List<CE> handlingCode;
    protected CE formCode;
    protected ST lotNumberText;
    protected IVLTS expirationTime;
    protected IVLTS stabilityTime;
    protected SC manufacturerModelName;
    protected SC softwareName;
    protected CE localRemoteControlStateCode;
    protected CE alertLevelCode;
    protected TS lastCalibrationTime;
    protected List<POQMMT000002UVPatientParticipation> asPatientParticipation;
    protected List<POQMMT000002UVLicensedEntityParticipation> asLicensedEntityParticipation;
    protected List<POQMMT000002UVEmploymentParticipation> asEmploymentParticipation;
    protected List<POQMMT000002UVQualifiedEntityParticipation> asQualifiedEntityParticipation;
    protected List<POQMMT000002UVAccessParticipation> asAccessParticipation;
    protected List<POQMMT000002UVRoleParticipation> asRoleParticipation;
    protected List<POQMMT000002UVRolePlayed> asRolePlayed;
    protected List<POQMMT000002UVPatientParticipation> patientParticipation;
    protected List<POQMMT000002UVLicensedEntityParticipation> licensedEntityParticipation;
    protected List<POQMMT000002UVEmploymentParticipation> employmentParticipation;
    protected List<POQMMT000002UVQualifiedEntityParticipation> qualifiedEntityParticipation;
    protected List<POQMMT000002UVAccessParticipation> accessParticipation;
    protected List<POQMMT000002UVRoleParticipation> roleParticipation;
    protected List<POQMMT000002UVRoleScoped> roleScoped;
    protected List<POQMMT000002UVLanguageCommunication> languageCommunication;
    @XmlAttribute(required = true)
    protected EntityClass classCode;
    @XmlAttribute(required = true)
    protected EntityDeterminer determinerCode;
    @XmlAttribute
    protected NullFlavor nullFlavor;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getId() {
        if (id == null) {
            id = new ArrayList<II>();
        }
        return this.id;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCode(CD value) {
        this.code = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setQuantity(PQ value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EN }
     * 
     * 
     */
    public List<EN> getName() {
        if (name == null) {
            name = new ArrayList<EN>();
        }
        return this.name;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link ED }
     *     
     */
    public ED getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ED }
     *     
     */
    public void setDesc(ED value) {
        this.desc = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setStatusCode(CS value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the existenceTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getExistenceTime() {
        return existenceTime;
    }

    /**
     * Sets the value of the existenceTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setExistenceTime(IVLTS value) {
        this.existenceTime = value;
    }

    /**
     * Gets the value of the telecom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telecom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelecom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEL }
     * 
     * 
     */
    public List<TEL> getTelecom() {
        if (telecom == null) {
            telecom = new ArrayList<TEL>();
        }
        return this.telecom;
    }

    /**
     * Gets the value of the riskCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the riskCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRiskCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CE }
     * 
     * 
     */
    public List<CE> getRiskCode() {
        if (riskCode == null) {
            riskCode = new ArrayList<CE>();
        }
        return this.riskCode;
    }

    /**
     * Gets the value of the handlingCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the handlingCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHandlingCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CE }
     * 
     * 
     */
    public List<CE> getHandlingCode() {
        if (handlingCode == null) {
            handlingCode = new ArrayList<CE>();
        }
        return this.handlingCode;
    }

    /**
     * Gets the value of the formCode property.
     * 
     * @return
     *     possible object is
     *     {@link CE }
     *     
     */
    public CE getFormCode() {
        return formCode;
    }

    /**
     * Sets the value of the formCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CE }
     *     
     */
    public void setFormCode(CE value) {
        this.formCode = value;
    }

    /**
     * Gets the value of the lotNumberText property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getLotNumberText() {
        return lotNumberText;
    }

    /**
     * Sets the value of the lotNumberText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setLotNumberText(ST value) {
        this.lotNumberText = value;
    }

    /**
     * Gets the value of the expirationTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getExpirationTime() {
        return expirationTime;
    }

    /**
     * Sets the value of the expirationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setExpirationTime(IVLTS value) {
        this.expirationTime = value;
    }

    /**
     * Gets the value of the stabilityTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getStabilityTime() {
        return stabilityTime;
    }

    /**
     * Sets the value of the stabilityTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setStabilityTime(IVLTS value) {
        this.stabilityTime = value;
    }

    /**
     * Gets the value of the manufacturerModelName property.
     * 
     * @return
     *     possible object is
     *     {@link SC }
     *     
     */
    public SC getManufacturerModelName() {
        return manufacturerModelName;
    }

    /**
     * Sets the value of the manufacturerModelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SC }
     *     
     */
    public void setManufacturerModelName(SC value) {
        this.manufacturerModelName = value;
    }

    /**
     * Gets the value of the softwareName property.
     * 
     * @return
     *     possible object is
     *     {@link SC }
     *     
     */
    public SC getSoftwareName() {
        return softwareName;
    }

    /**
     * Sets the value of the softwareName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SC }
     *     
     */
    public void setSoftwareName(SC value) {
        this.softwareName = value;
    }

    /**
     * Gets the value of the localRemoteControlStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link CE }
     *     
     */
    public CE getLocalRemoteControlStateCode() {
        return localRemoteControlStateCode;
    }

    /**
     * Sets the value of the localRemoteControlStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CE }
     *     
     */
    public void setLocalRemoteControlStateCode(CE value) {
        this.localRemoteControlStateCode = value;
    }

    /**
     * Gets the value of the alertLevelCode property.
     * 
     * @return
     *     possible object is
     *     {@link CE }
     *     
     */
    public CE getAlertLevelCode() {
        return alertLevelCode;
    }

    /**
     * Sets the value of the alertLevelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CE }
     *     
     */
    public void setAlertLevelCode(CE value) {
        this.alertLevelCode = value;
    }

    /**
     * Gets the value of the lastCalibrationTime property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getLastCalibrationTime() {
        return lastCalibrationTime;
    }

    /**
     * Sets the value of the lastCalibrationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setLastCalibrationTime(TS value) {
        this.lastCalibrationTime = value;
    }

    /**
     * Gets the value of the asPatientParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asPatientParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsPatientParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVPatientParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVPatientParticipation> getAsPatientParticipation() {
        if (asPatientParticipation == null) {
            asPatientParticipation = new ArrayList<POQMMT000002UVPatientParticipation>();
        }
        return this.asPatientParticipation;
    }

    /**
     * Gets the value of the asLicensedEntityParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asLicensedEntityParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsLicensedEntityParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVLicensedEntityParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVLicensedEntityParticipation> getAsLicensedEntityParticipation() {
        if (asLicensedEntityParticipation == null) {
            asLicensedEntityParticipation = new ArrayList<POQMMT000002UVLicensedEntityParticipation>();
        }
        return this.asLicensedEntityParticipation;
    }

    /**
     * Gets the value of the asEmploymentParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asEmploymentParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsEmploymentParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVEmploymentParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVEmploymentParticipation> getAsEmploymentParticipation() {
        if (asEmploymentParticipation == null) {
            asEmploymentParticipation = new ArrayList<POQMMT000002UVEmploymentParticipation>();
        }
        return this.asEmploymentParticipation;
    }

    /**
     * Gets the value of the asQualifiedEntityParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asQualifiedEntityParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsQualifiedEntityParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVQualifiedEntityParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVQualifiedEntityParticipation> getAsQualifiedEntityParticipation() {
        if (asQualifiedEntityParticipation == null) {
            asQualifiedEntityParticipation = new ArrayList<POQMMT000002UVQualifiedEntityParticipation>();
        }
        return this.asQualifiedEntityParticipation;
    }

    /**
     * Gets the value of the asAccessParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asAccessParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsAccessParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVAccessParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVAccessParticipation> getAsAccessParticipation() {
        if (asAccessParticipation == null) {
            asAccessParticipation = new ArrayList<POQMMT000002UVAccessParticipation>();
        }
        return this.asAccessParticipation;
    }

    /**
     * Gets the value of the asRoleParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asRoleParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsRoleParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVRoleParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVRoleParticipation> getAsRoleParticipation() {
        if (asRoleParticipation == null) {
            asRoleParticipation = new ArrayList<POQMMT000002UVRoleParticipation>();
        }
        return this.asRoleParticipation;
    }

    /**
     * Gets the value of the asRolePlayed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asRolePlayed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsRolePlayed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVRolePlayed }
     * 
     * 
     */
    public List<POQMMT000002UVRolePlayed> getAsRolePlayed() {
        if (asRolePlayed == null) {
            asRolePlayed = new ArrayList<POQMMT000002UVRolePlayed>();
        }
        return this.asRolePlayed;
    }

    /**
     * Gets the value of the patientParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patientParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatientParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVPatientParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVPatientParticipation> getPatientParticipation() {
        if (patientParticipation == null) {
            patientParticipation = new ArrayList<POQMMT000002UVPatientParticipation>();
        }
        return this.patientParticipation;
    }

    /**
     * Gets the value of the licensedEntityParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the licensedEntityParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLicensedEntityParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVLicensedEntityParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVLicensedEntityParticipation> getLicensedEntityParticipation() {
        if (licensedEntityParticipation == null) {
            licensedEntityParticipation = new ArrayList<POQMMT000002UVLicensedEntityParticipation>();
        }
        return this.licensedEntityParticipation;
    }

    /**
     * Gets the value of the employmentParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the employmentParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmploymentParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVEmploymentParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVEmploymentParticipation> getEmploymentParticipation() {
        if (employmentParticipation == null) {
            employmentParticipation = new ArrayList<POQMMT000002UVEmploymentParticipation>();
        }
        return this.employmentParticipation;
    }

    /**
     * Gets the value of the qualifiedEntityParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualifiedEntityParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualifiedEntityParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVQualifiedEntityParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVQualifiedEntityParticipation> getQualifiedEntityParticipation() {
        if (qualifiedEntityParticipation == null) {
            qualifiedEntityParticipation = new ArrayList<POQMMT000002UVQualifiedEntityParticipation>();
        }
        return this.qualifiedEntityParticipation;
    }

    /**
     * Gets the value of the accessParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVAccessParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVAccessParticipation> getAccessParticipation() {
        if (accessParticipation == null) {
            accessParticipation = new ArrayList<POQMMT000002UVAccessParticipation>();
        }
        return this.accessParticipation;
    }

    /**
     * Gets the value of the roleParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVRoleParticipation }
     * 
     * 
     */
    public List<POQMMT000002UVRoleParticipation> getRoleParticipation() {
        if (roleParticipation == null) {
            roleParticipation = new ArrayList<POQMMT000002UVRoleParticipation>();
        }
        return this.roleParticipation;
    }

    /**
     * Gets the value of the roleScoped property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleScoped property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleScoped().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVRoleScoped }
     * 
     * 
     */
    public List<POQMMT000002UVRoleScoped> getRoleScoped() {
        if (roleScoped == null) {
            roleScoped = new ArrayList<POQMMT000002UVRoleScoped>();
        }
        return this.roleScoped;
    }

    /**
     * Gets the value of the languageCommunication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageCommunication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageCommunication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVLanguageCommunication }
     * 
     * 
     */
    public List<POQMMT000002UVLanguageCommunication> getLanguageCommunication() {
        if (languageCommunication == null) {
            languageCommunication = new ArrayList<POQMMT000002UVLanguageCommunication>();
        }
        return this.languageCommunication;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link EntityClass }
     *     
     */
    public EntityClass getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityClass }
     *     
     */
    public void setClassCode(EntityClass value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the determinerCode property.
     * 
     * @return
     *     possible object is
     *     {@link EntityDeterminer }
     *     
     */
    public EntityDeterminer getDeterminerCode() {
        return determinerCode;
    }

    /**
     * Sets the value of the determinerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityDeterminer }
     *     
     */
    public void setDeterminerCode(EntityDeterminer value) {
        this.determinerCode = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * @return
     *     possible object is
     *     {@link NullFlavor }
     *     
     */
    public NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    /**
     * Sets the value of the nullFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullFlavor }
     *     
     */
    public void setNullFlavor(NullFlavor value) {
        this.nullFlavor = value;
    }

}
