//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 03:59:37 PM EST 
//


package edu.phema.jaxb.queryHealth.hqmf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for POQM_MT000001UV.Entry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POQM_MT000001UV.Entry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="localVariableName" type="{urn:hl7-org:v3}ST" minOccurs="0"/>
 *         &lt;element name="subsetCode" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="code" type="{urn:hl7-org:v3}ActRelationshipSubset" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="patientPopulationCriteria" type="{urn:hl7-org:v3}POQM_MT000002UV.PatientPopulationCriteria"/>
 *           &lt;element name="numeratorCriteria" type="{urn:hl7-org:v3}POQM_MT000002UV.NumeratorCriteria"/>
 *           &lt;element name="denominatorCriteria" type="{urn:hl7-org:v3}POQM_MT000002UV.DenominatorCriteria"/>
 *           &lt;element name="denominatorExceptionCriteria" type="{urn:hl7-org:v3}POQM_MT000002UV.DenominatorExceptionCriteria"/>
 *           &lt;element name="stratifierCriteria" type="{urn:hl7-org:v3}POQM_MT000002UV.StratifierCriteria"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="contextConductionInd" type="{urn:hl7-org:v3}bl" fixed="true" />
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *       &lt;attribute name="typeCode" type="{urn:hl7-org:v3}cs" default="COMP" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POQM_MT000001UV.Entry", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "localVariableName",
    "subsetCode",
    "patientPopulationCriteria",
    "numeratorCriteria",
    "denominatorCriteria",
    "denominatorExceptionCriteria",
    "stratifierCriteria"
})
public class POQMMT000001UVEntry {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    protected ST localVariableName;
    protected POQMMT000001UVEntry.SubsetCode subsetCode;
    protected POQMMT000002UVPatientPopulationCriteria patientPopulationCriteria;
    protected POQMMT000002UVNumeratorCriteria numeratorCriteria;
    protected POQMMT000002UVDenominatorCriteria denominatorCriteria;
    protected POQMMT000002UVDenominatorExceptionCriteria denominatorExceptionCriteria;
    protected POQMMT000002UVStratifierCriteria stratifierCriteria;
    @XmlAttribute
    protected Boolean contextConductionInd;
    @XmlAttribute
    protected NullFlavor nullFlavor;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeCode;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the localVariableName property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getLocalVariableName() {
        return localVariableName;
    }

    /**
     * Sets the value of the localVariableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setLocalVariableName(ST value) {
        this.localVariableName = value;
    }

    /**
     * Gets the value of the subsetCode property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000001UVEntry.SubsetCode }
     *     
     */
    public POQMMT000001UVEntry.SubsetCode getSubsetCode() {
        return subsetCode;
    }

    /**
     * Sets the value of the subsetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000001UVEntry.SubsetCode }
     *     
     */
    public void setSubsetCode(POQMMT000001UVEntry.SubsetCode value) {
        this.subsetCode = value;
    }

    /**
     * Gets the value of the patientPopulationCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPatientPopulationCriteria }
     *     
     */
    public POQMMT000002UVPatientPopulationCriteria getPatientPopulationCriteria() {
        return patientPopulationCriteria;
    }

    /**
     * Sets the value of the patientPopulationCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPatientPopulationCriteria }
     *     
     */
    public void setPatientPopulationCriteria(POQMMT000002UVPatientPopulationCriteria value) {
        this.patientPopulationCriteria = value;
    }

    /**
     * Gets the value of the numeratorCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVNumeratorCriteria }
     *     
     */
    public POQMMT000002UVNumeratorCriteria getNumeratorCriteria() {
        return numeratorCriteria;
    }

    /**
     * Sets the value of the numeratorCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVNumeratorCriteria }
     *     
     */
    public void setNumeratorCriteria(POQMMT000002UVNumeratorCriteria value) {
        this.numeratorCriteria = value;
    }

    /**
     * Gets the value of the denominatorCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVDenominatorCriteria }
     *     
     */
    public POQMMT000002UVDenominatorCriteria getDenominatorCriteria() {
        return denominatorCriteria;
    }

    /**
     * Sets the value of the denominatorCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVDenominatorCriteria }
     *     
     */
    public void setDenominatorCriteria(POQMMT000002UVDenominatorCriteria value) {
        this.denominatorCriteria = value;
    }

    /**
     * Gets the value of the denominatorExceptionCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVDenominatorExceptionCriteria }
     *     
     */
    public POQMMT000002UVDenominatorExceptionCriteria getDenominatorExceptionCriteria() {
        return denominatorExceptionCriteria;
    }

    /**
     * Sets the value of the denominatorExceptionCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVDenominatorExceptionCriteria }
     *     
     */
    public void setDenominatorExceptionCriteria(POQMMT000002UVDenominatorExceptionCriteria value) {
        this.denominatorExceptionCriteria = value;
    }

    /**
     * Gets the value of the stratifierCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVStratifierCriteria }
     *     
     */
    public POQMMT000002UVStratifierCriteria getStratifierCriteria() {
        return stratifierCriteria;
    }

    /**
     * Sets the value of the stratifierCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVStratifierCriteria }
     *     
     */
    public void setStratifierCriteria(POQMMT000002UVStratifierCriteria value) {
        this.stratifierCriteria = value;
    }

    /**
     * Gets the value of the contextConductionInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isContextConductionInd() {
        if (contextConductionInd == null) {
            return true;
        } else {
            return contextConductionInd;
        }
    }

    /**
     * Sets the value of the contextConductionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContextConductionInd(Boolean value) {
        this.contextConductionInd = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * @return
     *     possible object is
     *     {@link NullFlavor }
     *     
     */
    public NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    /**
     * Sets the value of the nullFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullFlavor }
     *     
     */
    public void setNullFlavor(NullFlavor value) {
        this.nullFlavor = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        if (typeCode == null) {
            return "COMP";
        } else {
            return typeCode;
        }
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="code" type="{urn:hl7-org:v3}ActRelationshipSubset" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SubsetCode {

        @XmlAttribute
        protected ActRelationshipSubset code;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link ActRelationshipSubset }
         *     
         */
        public ActRelationshipSubset getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActRelationshipSubset }
         *     
         */
        public void setCode(ActRelationshipSubset value) {
            this.code = value;
        }

    }

}
