//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.03 at 05:11:47 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.knime.org/2008/09/XMLConfig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.phema.jaxb.knime;
