//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 01:40:43 PM EST 
//


package edu.phema.jaxb.uvqm.hl7v3;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for ActClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActClass">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="ACT"/>
 *     &lt;enumeration value="COMPOSITION"/>
 *     &lt;enumeration value="CONTAINER"/>
 *     &lt;enumeration value="EXTRACT"/>
 *     &lt;enumeration value="FOLDER"/>
 *     &lt;enumeration value="GROUPER"/>
 *     &lt;enumeration value="ROIBND"/>
 *     &lt;enumeration value="ROIOVL"/>
 *     &lt;enumeration value="LLD"/>
 *     &lt;enumeration value="PRN"/>
 *     &lt;enumeration value="RLD"/>
 *     &lt;enumeration value="SFWL"/>
 *     &lt;enumeration value="SIT"/>
 *     &lt;enumeration value="STN"/>
 *     &lt;enumeration value="SUP"/>
 *     &lt;enumeration value="ACCM"/>
 *     &lt;enumeration value="ACCT"/>
 *     &lt;enumeration value="ACSN"/>
 *     &lt;enumeration value="ADJUD"/>
 *     &lt;enumeration value="CACT"/>
 *     &lt;enumeration value="CNTRCT"/>
 *     &lt;enumeration value="CONS"/>
 *     &lt;enumeration value="CONTREG"/>
 *     &lt;enumeration value="CTTEVENT"/>
 *     &lt;enumeration value="DISPACT"/>
 *     &lt;enumeration value="EXPOS"/>
 *     &lt;enumeration value="INC"/>
 *     &lt;enumeration value="INFRM"/>
 *     &lt;enumeration value="INVE"/>
 *     &lt;enumeration value="LIST"/>
 *     &lt;enumeration value="MPROT"/>
 *     &lt;enumeration value="OBS"/>
 *     &lt;enumeration value="PCPR"/>
 *     &lt;enumeration value="POLICY"/>
 *     &lt;enumeration value="PROC"/>
 *     &lt;enumeration value="REG"/>
 *     &lt;enumeration value="REV"/>
 *     &lt;enumeration value="SPCTRT"/>
 *     &lt;enumeration value="SPLY"/>
 *     &lt;enumeration value="STORE"/>
 *     &lt;enumeration value="SUBST"/>
 *     &lt;enumeration value="TRFR"/>
 *     &lt;enumeration value="TRNS"/>
 *     &lt;enumeration value="XACT"/>
 *     &lt;enumeration value="ACTN"/>
 *     &lt;enumeration value="INFO"/>
 *     &lt;enumeration value="STC"/>
 *     &lt;enumeration value="OUTB"/>
 *     &lt;enumeration value="FCNTRCT"/>
 *     &lt;enumeration value="DOC"/>
 *     &lt;enumeration value="CASE"/>
 *     &lt;enumeration value="CATEGORY"/>
 *     &lt;enumeration value="DOCBODY"/>
 *     &lt;enumeration value="DOCSECT"/>
 *     &lt;enumeration value="TOPIC"/>
 *     &lt;enumeration value="DOCCLIN"/>
 *     &lt;enumeration value="CDALVLONE"/>
 *     &lt;enumeration value="AEXPOS"/>
 *     &lt;enumeration value="TEXPOS"/>
 *     &lt;enumeration value="EHR"/>
 *     &lt;enumeration value="COV"/>
 *     &lt;enumeration value="DETPOL"/>
 *     &lt;enumeration value="EXP"/>
 *     &lt;enumeration value="LOC"/>
 *     &lt;enumeration value="PHN"/>
 *     &lt;enumeration value="POL"/>
 *     &lt;enumeration value="SEQ"/>
 *     &lt;enumeration value="SEQVAR"/>
 *     &lt;enumeration value="CLUSTER"/>
 *     &lt;enumeration value="ALRT"/>
 *     &lt;enumeration value="BATTERY"/>
 *     &lt;enumeration value="CLNTRL"/>
 *     &lt;enumeration value="CNOD"/>
 *     &lt;enumeration value="CONC"/>
 *     &lt;enumeration value="COND"/>
 *     &lt;enumeration value="DGIMG"/>
 *     &lt;enumeration value="GEN"/>
 *     &lt;enumeration value="INVSTG"/>
 *     &lt;enumeration value="OBSSER"/>
 *     &lt;enumeration value="POS"/>
 *     &lt;enumeration value="SPCOBS"/>
 *     &lt;enumeration value="VERIF"/>
 *     &lt;enumeration value="OBSCOR"/>
 *     &lt;enumeration value="ENC"/>
 *     &lt;enumeration value="JURISPOL"/>
 *     &lt;enumeration value="ORGPOL"/>
 *     &lt;enumeration value="SCOPOL"/>
 *     &lt;enumeration value="STDPOL"/>
 *     &lt;enumeration value="POSACC"/>
 *     &lt;enumeration value="POSCOORD"/>
 *     &lt;enumeration value="SBADM"/>
 *     &lt;enumeration value="SBEXT"/>
 *     &lt;enumeration value="SPECCOLLECT"/>
 *     &lt;enumeration value="DIET"/>
 *     &lt;enumeration value="RTRD"/>
 *     &lt;enumeration value="TRD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ActClass {

    ACT,
    COMPOSITION,
    CONTAINER,
    EXTRACT,
    FOLDER,
    GROUPER,
    ROIBND,
    ROIOVL,
    LLD,
    PRN,
    RLD,
    SFWL,
    SIT,
    STN,
    SUP,
    ACCM,
    ACCT,
    ACSN,
    ADJUD,
    CACT,
    CNTRCT,
    CONS,
    CONTREG,
    CTTEVENT,
    DISPACT,
    EXPOS,
    INC,
    INFRM,
    INVE,
    LIST,
    MPROT,
    OBS,
    PCPR,
    POLICY,
    PROC,
    REG,
    REV,
    SPCTRT,
    SPLY,
    STORE,
    SUBST,
    TRFR,
    TRNS,
    XACT,
    ACTN,
    INFO,
    STC,
    OUTB,
    FCNTRCT,
    DOC,
    CASE,
    CATEGORY,
    DOCBODY,
    DOCSECT,
    TOPIC,
    DOCCLIN,
    CDALVLONE,
    AEXPOS,
    TEXPOS,
    EHR,
    COV,
    DETPOL,
    EXP,
    LOC,
    PHN,
    POL,
    SEQ,
    SEQVAR,
    CLUSTER,
    ALRT,
    BATTERY,
    CLNTRL,
    CNOD,
    CONC,
    COND,
    DGIMG,
    GEN,
    INVSTG,
    OBSSER,
    POS,
    SPCOBS,
    VERIF,
    OBSCOR,
    ENC,
    JURISPOL,
    ORGPOL,
    SCOPOL,
    STDPOL,
    POSACC,
    POSCOORD,
    SBADM,
    SBEXT,
    SPECCOLLECT,
    DIET,
    RTRD,
    TRD;

    public String value() {
        return name();
    }

    public static ActClass fromValue(String v) {
        return valueOf(v);
    }

}
