//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 01:40:43 PM EST 
//


package edu.phema.jaxb.uvqm.hl7v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for ActRelationshipType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActRelationshipType">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="COMP"/>
 *     &lt;enumeration value="OUTC"/>
 *     &lt;enumeration value="PERT"/>
 *     &lt;enumeration value="SEQL"/>
 *     &lt;enumeration value="CONCURRENT"/>
 *     &lt;enumeration value="DURING"/>
 *     &lt;enumeration value="ECW"/>
 *     &lt;enumeration value="OVERLAP"/>
 *     &lt;enumeration value="SAE"/>
 *     &lt;enumeration value="SAS"/>
 *     &lt;enumeration value="SCW"/>
 *     &lt;enumeration value="CIND"/>
 *     &lt;enumeration value="PRCN"/>
 *     &lt;enumeration value="RSON"/>
 *     &lt;enumeration value="TRIG"/>
 *     &lt;enumeration value="CHRG"/>
 *     &lt;enumeration value="COST"/>
 *     &lt;enumeration value="CREDIT"/>
 *     &lt;enumeration value="DEBIT"/>
 *     &lt;enumeration value="OBJC"/>
 *     &lt;enumeration value="OBJF"/>
 *     &lt;enumeration value="ARR"/>
 *     &lt;enumeration value="CTRLV"/>
 *     &lt;enumeration value="DEP"/>
 *     &lt;enumeration value="OCCR"/>
 *     &lt;enumeration value="OREF"/>
 *     &lt;enumeration value="SCH"/>
 *     &lt;enumeration value="RCVY"/>
 *     &lt;enumeration value="GOAL"/>
 *     &lt;enumeration value="RISK"/>
 *     &lt;enumeration value="AUTH"/>
 *     &lt;enumeration value="CAUS"/>
 *     &lt;enumeration value="COVBY"/>
 *     &lt;enumeration value="DRIV"/>
 *     &lt;enumeration value="ELNK"/>
 *     &lt;enumeration value="EVID"/>
 *     &lt;enumeration value="EXACBY"/>
 *     &lt;enumeration value="EXPL"/>
 *     &lt;enumeration value="ITEMSLOC"/>
 *     &lt;enumeration value="LIMIT"/>
 *     &lt;enumeration value="MFST"/>
 *     &lt;enumeration value="NAME"/>
 *     &lt;enumeration value="PREV"/>
 *     &lt;enumeration value="REFR"/>
 *     &lt;enumeration value="REFV"/>
 *     &lt;enumeration value="RELVBY"/>
 *     &lt;enumeration value="SPRT"/>
 *     &lt;enumeration value="SUBJ"/>
 *     &lt;enumeration value="SUMM"/>
 *     &lt;enumeration value="BLOCK"/>
 *     &lt;enumeration value="CURE"/>
 *     &lt;enumeration value="CURE.ADJ"/>
 *     &lt;enumeration value="DIAG"/>
 *     &lt;enumeration value="MITGT"/>
 *     &lt;enumeration value="MTGT.ADJ"/>
 *     &lt;enumeration value="SYMP"/>
 *     &lt;enumeration value="APND"/>
 *     &lt;enumeration value="COMPLY"/>
 *     &lt;enumeration value="DOC"/>
 *     &lt;enumeration value="FLFS"/>
 *     &lt;enumeration value="GEN"/>
 *     &lt;enumeration value="GEVL"/>
 *     &lt;enumeration value="INST"/>
 *     &lt;enumeration value="MOD"/>
 *     &lt;enumeration value="MTCH"/>
 *     &lt;enumeration value="OPTN"/>
 *     &lt;enumeration value="RCHAL"/>
 *     &lt;enumeration value="REV"/>
 *     &lt;enumeration value="RPLC"/>
 *     &lt;enumeration value="SUCC"/>
 *     &lt;enumeration value="UPDT"/>
 *     &lt;enumeration value="XCRPT"/>
 *     &lt;enumeration value="XFRM"/>
 *     &lt;enumeration value="SPRTBND"/>
 *     &lt;enumeration value="VRXCRPT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ActRelationshipType {

    COMP("COMP"),
    OUTC("OUTC"),
    PERT("PERT"),
    SEQL("SEQL"),
    CONCURRENT("CONCURRENT"),
    DURING("DURING"),
    ECW("ECW"),
    OVERLAP("OVERLAP"),
    SAE("SAE"),
    SAS("SAS"),
    SCW("SCW"),
    CIND("CIND"),
    PRCN("PRCN"),
    RSON("RSON"),
    TRIG("TRIG"),
    CHRG("CHRG"),
    COST("COST"),
    CREDIT("CREDIT"),
    DEBIT("DEBIT"),
    OBJC("OBJC"),
    OBJF("OBJF"),
    ARR("ARR"),
    CTRLV("CTRLV"),
    DEP("DEP"),
    OCCR("OCCR"),
    OREF("OREF"),
    SCH("SCH"),
    RCVY("RCVY"),
    GOAL("GOAL"),
    RISK("RISK"),
    AUTH("AUTH"),
    CAUS("CAUS"),
    COVBY("COVBY"),
    DRIV("DRIV"),
    ELNK("ELNK"),
    EVID("EVID"),
    EXACBY("EXACBY"),
    EXPL("EXPL"),
    ITEMSLOC("ITEMSLOC"),
    LIMIT("LIMIT"),
    MFST("MFST"),
    NAME("NAME"),
    PREV("PREV"),
    REFR("REFR"),
    REFV("REFV"),
    RELVBY("RELVBY"),
    SPRT("SPRT"),
    SUBJ("SUBJ"),
    SUMM("SUMM"),
    BLOCK("BLOCK"),
    CURE("CURE"),
    @XmlEnumValue("CURE.ADJ")
    CURE_ADJ("CURE.ADJ"),
    DIAG("DIAG"),
    MITGT("MITGT"),
    @XmlEnumValue("MTGT.ADJ")
    MTGT_ADJ("MTGT.ADJ"),
    SYMP("SYMP"),
    APND("APND"),
    COMPLY("COMPLY"),
    DOC("DOC"),
    FLFS("FLFS"),
    GEN("GEN"),
    GEVL("GEVL"),
    INST("INST"),
    MOD("MOD"),
    MTCH("MTCH"),
    OPTN("OPTN"),
    RCHAL("RCHAL"),
    REV("REV"),
    RPLC("RPLC"),
    SUCC("SUCC"),
    UPDT("UPDT"),
    XCRPT("XCRPT"),
    XFRM("XFRM"),
    SPRTBND("SPRTBND"),
    VRXCRPT("VRXCRPT");
    private final String value;

    ActRelationshipType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActRelationshipType fromValue(String v) {
        for (ActRelationshipType c: ActRelationshipType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
