//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 01:40:43 PM EST 
//


package edu.phema.jaxb.uvqm.hl7v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POQM_MT000002UV.AccessParticipant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POQM_MT000002UV.AccessParticipant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="code" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="name" type="{urn:hl7-org:v3}EN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="addr" type="{urn:hl7-org:v3}AD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="telecom" type="{urn:hl7-org:v3}TEL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="statusCode" type="{urn:hl7-org:v3}CS" minOccurs="0"/>
 *         &lt;element name="effectiveTime" type="{urn:hl7-org:v3}IVL_TS" minOccurs="0"/>
 *         &lt;element name="certificateText" type="{urn:hl7-org:v3}ED" minOccurs="0"/>
 *         &lt;element name="confidentialityCode" type="{urn:hl7-org:v3}CE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="quantity" type="{urn:hl7-org:v3}RTO_PQ_PQ" minOccurs="0"/>
 *         &lt;element name="positionNumber" type="{urn:hl7-org:v3}INT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="approachSiteCode" type="{urn:hl7-org:v3}CD" minOccurs="0"/>
 *         &lt;element name="targetSiteCode" type="{urn:hl7-org:v3}CD" minOccurs="0"/>
 *         &lt;element name="gaugeQuantity" type="{urn:hl7-org:v3}PQ" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="accessContainer" type="{urn:hl7-org:v3}POQM_MT000002UV.Container" minOccurs="0"/>
 *           &lt;element name="accessManufacturedMaterial" type="{urn:hl7-org:v3}POQM_MT000002UV.ManufacturedMaterial" minOccurs="0"/>
 *           &lt;element name="accessDevice" type="{urn:hl7-org:v3}POQM_MT000002UV.Device" minOccurs="0"/>
 *           &lt;element name="accessPerson" type="{urn:hl7-org:v3}POQM_MT000002UV.Person" minOccurs="0"/>
 *           &lt;element name="accessNonPersonLivingSubject" type="{urn:hl7-org:v3}POQM_MT000002UV.NonPersonLivingSubject" minOccurs="0"/>
 *           &lt;element name="accessEntity" type="{urn:hl7-org:v3}POQM_MT000002UV.Entity" minOccurs="0"/>
 *           &lt;element name="accessMaterial" type="{urn:hl7-org:v3}POQM_MT000002UV.Material" minOccurs="0"/>
 *           &lt;element name="accessOrganization" type="{urn:hl7-org:v3}POQM_MT000002UV.Organization" minOccurs="0"/>
 *           &lt;element name="accessPlace" type="{urn:hl7-org:v3}POQM_MT000002UV.Place" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="accessedContainer" type="{urn:hl7-org:v3}POQM_MT000002UV.Container" minOccurs="0"/>
 *           &lt;element name="accessedManufacturedMaterial" type="{urn:hl7-org:v3}POQM_MT000002UV.ManufacturedMaterial" minOccurs="0"/>
 *           &lt;element name="accessedDevice" type="{urn:hl7-org:v3}POQM_MT000002UV.Device" minOccurs="0"/>
 *           &lt;element name="accessedPerson" type="{urn:hl7-org:v3}POQM_MT000002UV.Person" minOccurs="0"/>
 *           &lt;element name="accessedNonPersonLivingSubject" type="{urn:hl7-org:v3}POQM_MT000002UV.NonPersonLivingSubject" minOccurs="0"/>
 *           &lt;element name="accessedEntity" type="{urn:hl7-org:v3}POQM_MT000002UV.Entity" minOccurs="0"/>
 *           &lt;element name="accessedMaterial" type="{urn:hl7-org:v3}POQM_MT000002UV.Material" minOccurs="0"/>
 *           &lt;element name="accessedOrganization" type="{urn:hl7-org:v3}POQM_MT000002UV.Organization" minOccurs="0"/>
 *           &lt;element name="accessedPlace" type="{urn:hl7-org:v3}POQM_MT000002UV.Place" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="sourceOf" type="{urn:hl7-org:v3}POQM_MT000002UV.SourceOf3" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="targetOf" type="{urn:hl7-org:v3}POQM_MT000002UV.SourceOf4" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="classCode" use="required" type="{urn:hl7-org:v3}RoleClass" />
 *       &lt;attribute name="negationInd" type="{urn:hl7-org:v3}bl" />
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POQM_MT000002UV.AccessParticipant", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "id",
    "code",
    "name",
    "addr",
    "telecom",
    "statusCode",
    "effectiveTime",
    "certificateText",
    "confidentialityCode",
    "quantity",
    "positionNumber",
    "approachSiteCode",
    "targetSiteCode",
    "gaugeQuantity",
    "accessContainer",
    "accessManufacturedMaterial",
    "accessDevice",
    "accessPerson",
    "accessNonPersonLivingSubject",
    "accessEntity",
    "accessMaterial",
    "accessOrganization",
    "accessPlace",
    "accessedContainer",
    "accessedManufacturedMaterial",
    "accessedDevice",
    "accessedPerson",
    "accessedNonPersonLivingSubject",
    "accessedEntity",
    "accessedMaterial",
    "accessedOrganization",
    "accessedPlace",
    "sourceOf",
    "targetOf"
})
public class POQMMT000002UVAccessParticipant {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    protected List<II> id;
    protected CE code;
    protected List<EN> name;
    protected List<AD> addr;
    protected List<TEL> telecom;
    protected CS statusCode;
    protected IVLTS effectiveTime;
    protected ED certificateText;
    protected List<CE> confidentialityCode;
    protected RTOPQPQ quantity;
    protected List<INT> positionNumber;
    protected CD approachSiteCode;
    protected CD targetSiteCode;
    protected PQ gaugeQuantity;
    protected POQMMT000002UVContainer accessContainer;
    protected POQMMT000002UVManufacturedMaterial accessManufacturedMaterial;
    protected POQMMT000002UVDevice accessDevice;
    protected POQMMT000002UVPerson accessPerson;
    protected POQMMT000002UVNonPersonLivingSubject accessNonPersonLivingSubject;
    protected POQMMT000002UVEntity accessEntity;
    protected POQMMT000002UVMaterial accessMaterial;
    protected POQMMT000002UVOrganization accessOrganization;
    protected POQMMT000002UVPlace accessPlace;
    protected POQMMT000002UVContainer accessedContainer;
    protected POQMMT000002UVManufacturedMaterial accessedManufacturedMaterial;
    protected POQMMT000002UVDevice accessedDevice;
    protected POQMMT000002UVPerson accessedPerson;
    protected POQMMT000002UVNonPersonLivingSubject accessedNonPersonLivingSubject;
    protected POQMMT000002UVEntity accessedEntity;
    protected POQMMT000002UVMaterial accessedMaterial;
    protected POQMMT000002UVOrganization accessedOrganization;
    protected POQMMT000002UVPlace accessedPlace;
    protected List<POQMMT000002UVSourceOf3> sourceOf;
    protected List<POQMMT000002UVSourceOf4> targetOf;
    @XmlAttribute(required = true)
    protected RoleClass classCode;
    @XmlAttribute
    protected Boolean negationInd;
    @XmlAttribute
    protected NullFlavor nullFlavor;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getId() {
        if (id == null) {
            id = new ArrayList<II>();
        }
        return this.id;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CE }
     *     
     */
    public CE getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CE }
     *     
     */
    public void setCode(CE value) {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EN }
     * 
     * 
     */
    public List<EN> getName() {
        if (name == null) {
            name = new ArrayList<EN>();
        }
        return this.name;
    }

    /**
     * Gets the value of the addr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AD }
     * 
     * 
     */
    public List<AD> getAddr() {
        if (addr == null) {
            addr = new ArrayList<AD>();
        }
        return this.addr;
    }

    /**
     * Gets the value of the telecom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telecom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelecom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEL }
     * 
     * 
     */
    public List<TEL> getTelecom() {
        if (telecom == null) {
            telecom = new ArrayList<TEL>();
        }
        return this.telecom;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setStatusCode(CS value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the effectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * Sets the value of the effectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setEffectiveTime(IVLTS value) {
        this.effectiveTime = value;
    }

    /**
     * Gets the value of the certificateText property.
     * 
     * @return
     *     possible object is
     *     {@link ED }
     *     
     */
    public ED getCertificateText() {
        return certificateText;
    }

    /**
     * Sets the value of the certificateText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ED }
     *     
     */
    public void setCertificateText(ED value) {
        this.certificateText = value;
    }

    /**
     * Gets the value of the confidentialityCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the confidentialityCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfidentialityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CE }
     * 
     * 
     */
    public List<CE> getConfidentialityCode() {
        if (confidentialityCode == null) {
            confidentialityCode = new ArrayList<CE>();
        }
        return this.confidentialityCode;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link RTOPQPQ }
     *     
     */
    public RTOPQPQ getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTOPQPQ }
     *     
     */
    public void setQuantity(RTOPQPQ value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the positionNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the positionNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositionNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INT }
     * 
     * 
     */
    public List<INT> getPositionNumber() {
        if (positionNumber == null) {
            positionNumber = new ArrayList<INT>();
        }
        return this.positionNumber;
    }

    /**
     * Gets the value of the approachSiteCode property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getApproachSiteCode() {
        return approachSiteCode;
    }

    /**
     * Sets the value of the approachSiteCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setApproachSiteCode(CD value) {
        this.approachSiteCode = value;
    }

    /**
     * Gets the value of the targetSiteCode property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getTargetSiteCode() {
        return targetSiteCode;
    }

    /**
     * Sets the value of the targetSiteCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setTargetSiteCode(CD value) {
        this.targetSiteCode = value;
    }

    /**
     * Gets the value of the gaugeQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getGaugeQuantity() {
        return gaugeQuantity;
    }

    /**
     * Sets the value of the gaugeQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setGaugeQuantity(PQ value) {
        this.gaugeQuantity = value;
    }

    /**
     * Gets the value of the accessContainer property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVContainer }
     *     
     */
    public POQMMT000002UVContainer getAccessContainer() {
        return accessContainer;
    }

    /**
     * Sets the value of the accessContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVContainer }
     *     
     */
    public void setAccessContainer(POQMMT000002UVContainer value) {
        this.accessContainer = value;
    }

    /**
     * Gets the value of the accessManufacturedMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVManufacturedMaterial }
     *     
     */
    public POQMMT000002UVManufacturedMaterial getAccessManufacturedMaterial() {
        return accessManufacturedMaterial;
    }

    /**
     * Sets the value of the accessManufacturedMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVManufacturedMaterial }
     *     
     */
    public void setAccessManufacturedMaterial(POQMMT000002UVManufacturedMaterial value) {
        this.accessManufacturedMaterial = value;
    }

    /**
     * Gets the value of the accessDevice property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVDevice }
     *     
     */
    public POQMMT000002UVDevice getAccessDevice() {
        return accessDevice;
    }

    /**
     * Sets the value of the accessDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVDevice }
     *     
     */
    public void setAccessDevice(POQMMT000002UVDevice value) {
        this.accessDevice = value;
    }

    /**
     * Gets the value of the accessPerson property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPerson }
     *     
     */
    public POQMMT000002UVPerson getAccessPerson() {
        return accessPerson;
    }

    /**
     * Sets the value of the accessPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPerson }
     *     
     */
    public void setAccessPerson(POQMMT000002UVPerson value) {
        this.accessPerson = value;
    }

    /**
     * Gets the value of the accessNonPersonLivingSubject property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVNonPersonLivingSubject }
     *     
     */
    public POQMMT000002UVNonPersonLivingSubject getAccessNonPersonLivingSubject() {
        return accessNonPersonLivingSubject;
    }

    /**
     * Sets the value of the accessNonPersonLivingSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVNonPersonLivingSubject }
     *     
     */
    public void setAccessNonPersonLivingSubject(POQMMT000002UVNonPersonLivingSubject value) {
        this.accessNonPersonLivingSubject = value;
    }

    /**
     * Gets the value of the accessEntity property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVEntity }
     *     
     */
    public POQMMT000002UVEntity getAccessEntity() {
        return accessEntity;
    }

    /**
     * Sets the value of the accessEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVEntity }
     *     
     */
    public void setAccessEntity(POQMMT000002UVEntity value) {
        this.accessEntity = value;
    }

    /**
     * Gets the value of the accessMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVMaterial }
     *     
     */
    public POQMMT000002UVMaterial getAccessMaterial() {
        return accessMaterial;
    }

    /**
     * Sets the value of the accessMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVMaterial }
     *     
     */
    public void setAccessMaterial(POQMMT000002UVMaterial value) {
        this.accessMaterial = value;
    }

    /**
     * Gets the value of the accessOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVOrganization }
     *     
     */
    public POQMMT000002UVOrganization getAccessOrganization() {
        return accessOrganization;
    }

    /**
     * Sets the value of the accessOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVOrganization }
     *     
     */
    public void setAccessOrganization(POQMMT000002UVOrganization value) {
        this.accessOrganization = value;
    }

    /**
     * Gets the value of the accessPlace property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPlace }
     *     
     */
    public POQMMT000002UVPlace getAccessPlace() {
        return accessPlace;
    }

    /**
     * Sets the value of the accessPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPlace }
     *     
     */
    public void setAccessPlace(POQMMT000002UVPlace value) {
        this.accessPlace = value;
    }

    /**
     * Gets the value of the accessedContainer property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVContainer }
     *     
     */
    public POQMMT000002UVContainer getAccessedContainer() {
        return accessedContainer;
    }

    /**
     * Sets the value of the accessedContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVContainer }
     *     
     */
    public void setAccessedContainer(POQMMT000002UVContainer value) {
        this.accessedContainer = value;
    }

    /**
     * Gets the value of the accessedManufacturedMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVManufacturedMaterial }
     *     
     */
    public POQMMT000002UVManufacturedMaterial getAccessedManufacturedMaterial() {
        return accessedManufacturedMaterial;
    }

    /**
     * Sets the value of the accessedManufacturedMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVManufacturedMaterial }
     *     
     */
    public void setAccessedManufacturedMaterial(POQMMT000002UVManufacturedMaterial value) {
        this.accessedManufacturedMaterial = value;
    }

    /**
     * Gets the value of the accessedDevice property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVDevice }
     *     
     */
    public POQMMT000002UVDevice getAccessedDevice() {
        return accessedDevice;
    }

    /**
     * Sets the value of the accessedDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVDevice }
     *     
     */
    public void setAccessedDevice(POQMMT000002UVDevice value) {
        this.accessedDevice = value;
    }

    /**
     * Gets the value of the accessedPerson property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPerson }
     *     
     */
    public POQMMT000002UVPerson getAccessedPerson() {
        return accessedPerson;
    }

    /**
     * Sets the value of the accessedPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPerson }
     *     
     */
    public void setAccessedPerson(POQMMT000002UVPerson value) {
        this.accessedPerson = value;
    }

    /**
     * Gets the value of the accessedNonPersonLivingSubject property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVNonPersonLivingSubject }
     *     
     */
    public POQMMT000002UVNonPersonLivingSubject getAccessedNonPersonLivingSubject() {
        return accessedNonPersonLivingSubject;
    }

    /**
     * Sets the value of the accessedNonPersonLivingSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVNonPersonLivingSubject }
     *     
     */
    public void setAccessedNonPersonLivingSubject(POQMMT000002UVNonPersonLivingSubject value) {
        this.accessedNonPersonLivingSubject = value;
    }

    /**
     * Gets the value of the accessedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVEntity }
     *     
     */
    public POQMMT000002UVEntity getAccessedEntity() {
        return accessedEntity;
    }

    /**
     * Sets the value of the accessedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVEntity }
     *     
     */
    public void setAccessedEntity(POQMMT000002UVEntity value) {
        this.accessedEntity = value;
    }

    /**
     * Gets the value of the accessedMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVMaterial }
     *     
     */
    public POQMMT000002UVMaterial getAccessedMaterial() {
        return accessedMaterial;
    }

    /**
     * Sets the value of the accessedMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVMaterial }
     *     
     */
    public void setAccessedMaterial(POQMMT000002UVMaterial value) {
        this.accessedMaterial = value;
    }

    /**
     * Gets the value of the accessedOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVOrganization }
     *     
     */
    public POQMMT000002UVOrganization getAccessedOrganization() {
        return accessedOrganization;
    }

    /**
     * Sets the value of the accessedOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVOrganization }
     *     
     */
    public void setAccessedOrganization(POQMMT000002UVOrganization value) {
        this.accessedOrganization = value;
    }

    /**
     * Gets the value of the accessedPlace property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPlace }
     *     
     */
    public POQMMT000002UVPlace getAccessedPlace() {
        return accessedPlace;
    }

    /**
     * Sets the value of the accessedPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPlace }
     *     
     */
    public void setAccessedPlace(POQMMT000002UVPlace value) {
        this.accessedPlace = value;
    }

    /**
     * Gets the value of the sourceOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVSourceOf3 }
     * 
     * 
     */
    public List<POQMMT000002UVSourceOf3> getSourceOf() {
        if (sourceOf == null) {
            sourceOf = new ArrayList<POQMMT000002UVSourceOf3>();
        }
        return this.sourceOf;
    }

    /**
     * Gets the value of the targetOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POQMMT000002UVSourceOf4 }
     * 
     * 
     */
    public List<POQMMT000002UVSourceOf4> getTargetOf() {
        if (targetOf == null) {
            targetOf = new ArrayList<POQMMT000002UVSourceOf4>();
        }
        return this.targetOf;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link RoleClass }
     *     
     */
    public RoleClass getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleClass }
     *     
     */
    public void setClassCode(RoleClass value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the negationInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNegationInd() {
        return negationInd;
    }

    /**
     * Sets the value of the negationInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNegationInd(Boolean value) {
        this.negationInd = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * @return
     *     possible object is
     *     {@link NullFlavor }
     *     
     */
    public NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    /**
     * Sets the value of the nullFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullFlavor }
     *     
     */
    public void setNullFlavor(NullFlavor value) {
        this.nullFlavor = value;
    }

}
