//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 01:40:43 PM EST 
//


package edu.phema.jaxb.uvqm.hl7v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POQM_MT000002UV.Participant3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POQM_MT000002UV.Participant3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="functionCode" type="{urn:hl7-org:v3}CD" minOccurs="0"/>
 *         &lt;element name="sequenceNumber" type="{urn:hl7-org:v3}INT" minOccurs="0"/>
 *         &lt;element name="noteText" type="{urn:hl7-org:v3}ED" minOccurs="0"/>
 *         &lt;element name="time" type="{urn:hl7-org:v3}IVL_TS" minOccurs="0"/>
 *         &lt;element name="modeCode" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="awarenessCode" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="signatureCode" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="signatureText" type="{urn:hl7-org:v3}ED" minOccurs="0"/>
 *         &lt;element name="performInd" type="{urn:hl7-org:v3}BL" minOccurs="0"/>
 *         &lt;element name="substitutionConditionCode" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="subsetCode" type="{urn:hl7-org:v3}CS" minOccurs="0"/>
 *         &lt;element name="criterionInd" type="{urn:hl7-org:v3}BL" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="act" type="{urn:hl7-org:v3}POQM_MT000002UV.Act"/>
 *           &lt;element name="procedure" type="{urn:hl7-org:v3}POQM_MT000002UV.Procedure"/>
 *           &lt;element name="substanceAdministration" type="{urn:hl7-org:v3}POQM_MT000002UV.SubstanceAdministration"/>
 *           &lt;element name="observation" type="{urn:hl7-org:v3}POQM_MT000002UV.Observation"/>
 *           &lt;element name="encounter" type="{urn:hl7-org:v3}POQM_MT000002UV.Encounter"/>
 *           &lt;element name="diagnosticImage" type="{urn:hl7-org:v3}POQM_MT000002UV.DiagnosticImage"/>
 *           &lt;element name="supply" type="{urn:hl7-org:v3}POQM_MT000002UV.Supply"/>
 *           &lt;element name="exposure" type="{urn:hl7-org:v3}POQM_MT000002UV.Exposure"/>
 *           &lt;element name="document" type="{urn:hl7-org:v3}POQM_MT000002UV.Document"/>
 *           &lt;element name="financialContract" type="{urn:hl7-org:v3}POQM_MT000002UV.FinancialContract"/>
 *           &lt;element name="invoiceElement" type="{urn:hl7-org:v3}POQM_MT000002UV.InvoiceElement"/>
 *           &lt;element name="account" type="{urn:hl7-org:v3}POQM_MT000002UV.Account"/>
 *           &lt;element name="financialTransaction" type="{urn:hl7-org:v3}POQM_MT000002UV.FinancialTransaction"/>
 *           &lt;element name="publicHealthCase" type="{urn:hl7-org:v3}POQM_MT000002UV.PublicHealthCase"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="contextControlCode" type="{urn:hl7-org:v3}ContextControl" default="OP" />
 *       &lt;attribute name="negationInd" type="{urn:hl7-org:v3}bl" />
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *       &lt;attribute name="typeCode" use="required" type="{urn:hl7-org:v3}ParticipationType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POQM_MT000002UV.Participant3", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "functionCode",
    "sequenceNumber",
    "noteText",
    "time",
    "modeCode",
    "awarenessCode",
    "signatureCode",
    "signatureText",
    "performInd",
    "substitutionConditionCode",
    "subsetCode",
    "criterionInd",
    "act",
    "procedure",
    "substanceAdministration",
    "observation",
    "encounter",
    "diagnosticImage",
    "supply",
    "exposure",
    "document",
    "financialContract",
    "invoiceElement",
    "account",
    "financialTransaction",
    "publicHealthCase"
})
public class POQMMT000002UVParticipant3 {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    protected CD functionCode;
    protected INT sequenceNumber;
    protected ED noteText;
    protected IVLTS time;
    protected CE modeCode;
    protected CE awarenessCode;
    protected CE signatureCode;
    protected ED signatureText;
    protected BL performInd;
    protected CE substitutionConditionCode;
    protected CS subsetCode;
    protected BL criterionInd;
    protected POQMMT000002UVAct act;
    protected POQMMT000002UVProcedure procedure;
    protected POQMMT000002UVSubstanceAdministration substanceAdministration;
    protected POQMMT000002UVObservation observation;
    protected POQMMT000002UVEncounter encounter;
    protected POQMMT000002UVDiagnosticImage diagnosticImage;
    protected POQMMT000002UVSupply supply;
    protected POQMMT000002UVExposure exposure;
    protected POQMMT000002UVDocument document;
    protected POQMMT000002UVFinancialContract financialContract;
    protected POQMMT000002UVInvoiceElement invoiceElement;
    protected POQMMT000002UVAccount account;
    protected POQMMT000002UVFinancialTransaction financialTransaction;
    protected POQMMT000002UVPublicHealthCase publicHealthCase;
    @XmlAttribute
    protected ContextControl contextControlCode;
    @XmlAttribute
    protected Boolean negationInd;
    @XmlAttribute
    protected NullFlavor nullFlavor;
    @XmlAttribute(required = true)
    protected ParticipationType typeCode;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the functionCode property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getFunctionCode() {
        return functionCode;
    }

    /**
     * Sets the value of the functionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setFunctionCode(CD value) {
        this.functionCode = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setSequenceNumber(INT value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the noteText property.
     * 
     * @return
     *     possible object is
     *     {@link ED }
     *     
     */
    public ED getNoteText() {
        return noteText;
    }

    /**
     * Sets the value of the noteText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ED }
     *     
     */
    public void setNoteText(ED value) {
        this.noteText = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setTime(IVLTS value) {
        this.time = value;
    }

    /**
     * Gets the value of the modeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CE }
     *     
     */
    public CE getModeCode() {
        return modeCode;
    }

    /**
     * Sets the value of the modeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CE }
     *     
     */
    public void setModeCode(CE value) {
        this.modeCode = value;
    }

    /**
     * Gets the value of the awarenessCode property.
     * 
     * @return
     *     possible object is
     *     {@link CE }
     *     
     */
    public CE getAwarenessCode() {
        return awarenessCode;
    }

    /**
     * Sets the value of the awarenessCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CE }
     *     
     */
    public void setAwarenessCode(CE value) {
        this.awarenessCode = value;
    }

    /**
     * Gets the value of the signatureCode property.
     * 
     * @return
     *     possible object is
     *     {@link CE }
     *     
     */
    public CE getSignatureCode() {
        return signatureCode;
    }

    /**
     * Sets the value of the signatureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CE }
     *     
     */
    public void setSignatureCode(CE value) {
        this.signatureCode = value;
    }

    /**
     * Gets the value of the signatureText property.
     * 
     * @return
     *     possible object is
     *     {@link ED }
     *     
     */
    public ED getSignatureText() {
        return signatureText;
    }

    /**
     * Sets the value of the signatureText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ED }
     *     
     */
    public void setSignatureText(ED value) {
        this.signatureText = value;
    }

    /**
     * Gets the value of the performInd property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getPerformInd() {
        return performInd;
    }

    /**
     * Sets the value of the performInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setPerformInd(BL value) {
        this.performInd = value;
    }

    /**
     * Gets the value of the substitutionConditionCode property.
     * 
     * @return
     *     possible object is
     *     {@link CE }
     *     
     */
    public CE getSubstitutionConditionCode() {
        return substitutionConditionCode;
    }

    /**
     * Sets the value of the substitutionConditionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CE }
     *     
     */
    public void setSubstitutionConditionCode(CE value) {
        this.substitutionConditionCode = value;
    }

    /**
     * Gets the value of the subsetCode property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getSubsetCode() {
        return subsetCode;
    }

    /**
     * Sets the value of the subsetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setSubsetCode(CS value) {
        this.subsetCode = value;
    }

    /**
     * Gets the value of the criterionInd property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getCriterionInd() {
        return criterionInd;
    }

    /**
     * Sets the value of the criterionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setCriterionInd(BL value) {
        this.criterionInd = value;
    }

    /**
     * Gets the value of the act property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVAct }
     *     
     */
    public POQMMT000002UVAct getAct() {
        return act;
    }

    /**
     * Sets the value of the act property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVAct }
     *     
     */
    public void setAct(POQMMT000002UVAct value) {
        this.act = value;
    }

    /**
     * Gets the value of the procedure property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVProcedure }
     *     
     */
    public POQMMT000002UVProcedure getProcedure() {
        return procedure;
    }

    /**
     * Sets the value of the procedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVProcedure }
     *     
     */
    public void setProcedure(POQMMT000002UVProcedure value) {
        this.procedure = value;
    }

    /**
     * Gets the value of the substanceAdministration property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVSubstanceAdministration }
     *     
     */
    public POQMMT000002UVSubstanceAdministration getSubstanceAdministration() {
        return substanceAdministration;
    }

    /**
     * Sets the value of the substanceAdministration property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVSubstanceAdministration }
     *     
     */
    public void setSubstanceAdministration(POQMMT000002UVSubstanceAdministration value) {
        this.substanceAdministration = value;
    }

    /**
     * Gets the value of the observation property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVObservation }
     *     
     */
    public POQMMT000002UVObservation getObservation() {
        return observation;
    }

    /**
     * Sets the value of the observation property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVObservation }
     *     
     */
    public void setObservation(POQMMT000002UVObservation value) {
        this.observation = value;
    }

    /**
     * Gets the value of the encounter property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVEncounter }
     *     
     */
    public POQMMT000002UVEncounter getEncounter() {
        return encounter;
    }

    /**
     * Sets the value of the encounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVEncounter }
     *     
     */
    public void setEncounter(POQMMT000002UVEncounter value) {
        this.encounter = value;
    }

    /**
     * Gets the value of the diagnosticImage property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVDiagnosticImage }
     *     
     */
    public POQMMT000002UVDiagnosticImage getDiagnosticImage() {
        return diagnosticImage;
    }

    /**
     * Sets the value of the diagnosticImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVDiagnosticImage }
     *     
     */
    public void setDiagnosticImage(POQMMT000002UVDiagnosticImage value) {
        this.diagnosticImage = value;
    }

    /**
     * Gets the value of the supply property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVSupply }
     *     
     */
    public POQMMT000002UVSupply getSupply() {
        return supply;
    }

    /**
     * Sets the value of the supply property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVSupply }
     *     
     */
    public void setSupply(POQMMT000002UVSupply value) {
        this.supply = value;
    }

    /**
     * Gets the value of the exposure property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVExposure }
     *     
     */
    public POQMMT000002UVExposure getExposure() {
        return exposure;
    }

    /**
     * Sets the value of the exposure property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVExposure }
     *     
     */
    public void setExposure(POQMMT000002UVExposure value) {
        this.exposure = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVDocument }
     *     
     */
    public POQMMT000002UVDocument getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVDocument }
     *     
     */
    public void setDocument(POQMMT000002UVDocument value) {
        this.document = value;
    }

    /**
     * Gets the value of the financialContract property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVFinancialContract }
     *     
     */
    public POQMMT000002UVFinancialContract getFinancialContract() {
        return financialContract;
    }

    /**
     * Sets the value of the financialContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVFinancialContract }
     *     
     */
    public void setFinancialContract(POQMMT000002UVFinancialContract value) {
        this.financialContract = value;
    }

    /**
     * Gets the value of the invoiceElement property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVInvoiceElement }
     *     
     */
    public POQMMT000002UVInvoiceElement getInvoiceElement() {
        return invoiceElement;
    }

    /**
     * Sets the value of the invoiceElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVInvoiceElement }
     *     
     */
    public void setInvoiceElement(POQMMT000002UVInvoiceElement value) {
        this.invoiceElement = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVAccount }
     *     
     */
    public POQMMT000002UVAccount getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVAccount }
     *     
     */
    public void setAccount(POQMMT000002UVAccount value) {
        this.account = value;
    }

    /**
     * Gets the value of the financialTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVFinancialTransaction }
     *     
     */
    public POQMMT000002UVFinancialTransaction getFinancialTransaction() {
        return financialTransaction;
    }

    /**
     * Sets the value of the financialTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVFinancialTransaction }
     *     
     */
    public void setFinancialTransaction(POQMMT000002UVFinancialTransaction value) {
        this.financialTransaction = value;
    }

    /**
     * Gets the value of the publicHealthCase property.
     * 
     * @return
     *     possible object is
     *     {@link POQMMT000002UVPublicHealthCase }
     *     
     */
    public POQMMT000002UVPublicHealthCase getPublicHealthCase() {
        return publicHealthCase;
    }

    /**
     * Sets the value of the publicHealthCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link POQMMT000002UVPublicHealthCase }
     *     
     */
    public void setPublicHealthCase(POQMMT000002UVPublicHealthCase value) {
        this.publicHealthCase = value;
    }

    /**
     * Gets the value of the contextControlCode property.
     * 
     * @return
     *     possible object is
     *     {@link ContextControl }
     *     
     */
    public ContextControl getContextControlCode() {
        if (contextControlCode == null) {
            return ContextControl.OP;
        } else {
            return contextControlCode;
        }
    }

    /**
     * Sets the value of the contextControlCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextControl }
     *     
     */
    public void setContextControlCode(ContextControl value) {
        this.contextControlCode = value;
    }

    /**
     * Gets the value of the negationInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNegationInd() {
        return negationInd;
    }

    /**
     * Sets the value of the negationInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNegationInd(Boolean value) {
        this.negationInd = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * @return
     *     possible object is
     *     {@link NullFlavor }
     *     
     */
    public NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    /**
     * Sets the value of the nullFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullFlavor }
     *     
     */
    public void setNullFlavor(NullFlavor value) {
        this.nullFlavor = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipationType }
     *     
     */
    public ParticipationType getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipationType }
     *     
     */
    public void setTypeCode(ParticipationType value) {
        this.typeCode = value;
    }

}
