//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 01:40:43 PM EST 
//


package edu.phema.jaxb.uvqm.hl7v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for TelecommunicationCapabilities.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TelecommunicationCapabilities">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="voice"/>
 *     &lt;enumeration value="fax"/>
 *     &lt;enumeration value="data"/>
 *     &lt;enumeration value="sms"/>
 *     &lt;enumeration value="tty"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TelecommunicationCapabilities {

    @XmlEnumValue("voice")
    VOICE("voice"),
    @XmlEnumValue("fax")
    FAX("fax"),
    @XmlEnumValue("data")
    DATA("data"),
    @XmlEnumValue("sms")
    SMS("sms"),
    @XmlEnumValue("tty")
    TTY("tty");
    private final String value;

    TelecommunicationCapabilities(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TelecommunicationCapabilities fromValue(String v) {
        for (TelecommunicationCapabilities c: TelecommunicationCapabilities.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
