//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.15 at 03:09:44 PM CST 
//


package edu.phema.jaxb.ihe.svs;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for ActInvoicePaymentCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActInvoicePaymentCode">
 *   &lt;restriction base="{urn:ihe:iti:svs:2008}cs">
 *     &lt;enumeration value="BONUS"/>
 *     &lt;enumeration value="CFWD"/>
 *     &lt;enumeration value="EPYMT"/>
 *     &lt;enumeration value="EDU"/>
 *     &lt;enumeration value="GARN"/>
 *     &lt;enumeration value="PINV"/>
 *     &lt;enumeration value="PPRD"/>
 *     &lt;enumeration value="PROA"/>
 *     &lt;enumeration value="RECOV"/>
 *     &lt;enumeration value="RETRO"/>
 *     &lt;enumeration value="INVOICE"/>
 *     &lt;enumeration value="TRAN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ActInvoicePaymentCode {

    BONUS,
    CFWD,
    EPYMT,
    EDU,
    GARN,
    PINV,
    PPRD,
    PROA,
    RECOV,
    RETRO,
    INVOICE,
    TRAN;

    public String value() {
        return name();
    }

    public static ActInvoicePaymentCode fromValue(String v) {
        return valueOf(v);
    }

}
