//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.15 at 03:09:44 PM CST 
//


package edu.phema.jaxb.ihe.svs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for MdfHmdRowType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MdfHmdRowType">
 *   &lt;restriction base="{urn:ihe:iti:svs:2008}cs">
 *     &lt;enumeration value="assoc"/>
 *     &lt;enumeration value="attr"/>
 *     &lt;enumeration value="item"/>
 *     &lt;enumeration value="hmd"/>
 *     &lt;enumeration value="class"/>
 *     &lt;enumeration value="stc"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum MdfHmdRowType {

    @XmlEnumValue("assoc")
    ASSOC("assoc"),
    @XmlEnumValue("attr")
    ATTR("attr"),
    @XmlEnumValue("item")
    ITEM("item"),
    @XmlEnumValue("hmd")
    HMD("hmd"),
    @XmlEnumValue("class")
    CLASS("class"),
    @XmlEnumValue("stc")
    STC("stc");
    private final String value;

    MdfHmdRowType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MdfHmdRowType fromValue(String v) {
        for (MdfHmdRowType c: MdfHmdRowType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
